// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyUSf0FyXQJ56mrd2s4asHu6t4r00eNo8',
    appId: '1:915731393585:web:c32e69dfbfd540595ff910',
    messagingSenderId: '915731393585',
    projectId: 'loa-market-b8562',
    authDomain: 'loa-market-b8562.firebaseapp.com',
    storageBucket: 'loa-market-b8562.firebasestorage.app',
    measurementId: 'G-PS2TL6SNHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDay7b5nj7OKwChQayyDhuNX3OlssHAe08',
    appId: '1:915731393585:android:d1a4581549f56b425ff910',
    messagingSenderId: '915731393585',
    projectId: 'loa-market-b8562',
    storageBucket: 'loa-market-b8562.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBFNbtAaJGrR04i51fMBAwMw21EzYfrAA',
    appId: '1:915731393585:ios:a08d102588efb1875ff910',
    messagingSenderId: '915731393585',
    projectId: 'loa-market-b8562',
    storageBucket: 'loa-market-b8562.firebasestorage.app',
    iosBundleId: 'com.example.loaMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBFNbtAaJGrR04i51fMBAwMw21EzYfrAA',
    appId: '1:915731393585:ios:a08d102588efb1875ff910',
    messagingSenderId: '915731393585',
    projectId: 'loa-market-b8562',
    storageBucket: 'loa-market-b8562.firebasestorage.app',
    iosBundleId: 'com.example.loaMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyUSf0FyXQJ56mrd2s4asHu6t4r00eNo8',
    appId: '1:915731393585:web:763bb0ee04f8bb695ff910',
    messagingSenderId: '915731393585',
    projectId: 'loa-market-b8562',
    authDomain: 'loa-market-b8562.firebaseapp.com',
    storageBucket: 'loa-market-b8562.firebasestorage.app',
    measurementId: 'G-WY2VB1LWZC',
  );
}
